#Identificarlos
S = 0
D = 1
I = 2
I1 = 3
I2 = 4
R = 5
A = 6
A1 = 7
E = 8
E1 = 9
T = 10
T1 = 11
F = 12
C = 13
L = 14
W = 15
#Tabla LL 1 CONSTRUIDA CON LA GRAMATICA
tabla2 = [
    # Start
    [S, "SEMICOLON", None],
    [S, "IF", [D, S]],
    [S, "LPAREN", None],
    [S, "RPAREN", None],
    [S, "LBRACE", None],
    [S, "RBRACE", None],
    [S, "ELSE", None],
    [S, "WHILE", [D, S]],
    [S, "INT", [D, S]],
    [S, "FLOAT", [D, S]],
    [S, "CHAR", [D, S]],
    [S, "VOID", [D, S]],
    [S, "ID", [D, S]],
    [S, "ASSIGN", None],
    [S, "COMMA", None],
    [S, "PLUS", None],
    [S, "MINUS", None],
    [S, "TIMES", None],
    [S, "DIVIDE", None],
    [S, "NUMBER", None],
    [S, "LETTER", None],
    [S, "EQUALS", None],
    [S, "AND", None],
    [S, "OR", None],
    [S, "EOF", ["vacia"]],
    # Declaration
    [D, "SEMICOLON", None],
    [D, "IF", [I]],
    [D, "LPAREN", None],
    [D, "RPAREN", None],
    [D, "LBRACE", None],
    [D, "RBRACE", None],
    [D, "ELSE", None],
    [D, "WHILE", [W]],
    [D, "INT", [R, A, "SEMICOLON"]],
    [D, "FLOAT", [R, A, "SEMICOLON"]],
    [D, "CHAR", [R, A, "SEMICOLON"]],
    [D, "VOID", [R, A, "SEMICOLON"]],
    [D, "ID", [A, "SEMICOLON"]],
    [D, "ASSIGN", None],
    [D, "COMMA", None],
    [D, "PLUS", None],
    [D, "MINUS", None],
    [D, "TIMES", None],
    [D, "DIVIDE", None],
    [D, "NUMBER", None],
    [D, "LETTER", None],
    [D, "EQUALS", None],
    [D, "AND", None],
    [D, "OR", None],
    [D, "EOF", None],
    # If statement
    [I, "SEMICOLON", None],
    [I, "IF", ["IF", "LPAREN", E, "RPAREN", "LBRACE", I1, "RBRACE", I2]],
    [I, "LPAREN", None],
    [I, "RPAREN", None],
    [I, "LBRACE", None],
    [I, "RBRACE", None],
    [I, "ELSE", None],
    [I, "INT", None],
    [I, "FLOAT", None],
    [I, "CHAR", None],
    [I, "VOID", None],
    [I, "ID", None],
    [I, "ASSIGN", None],
    [I, "COMMA", None],
    [I, "PLUS", None],
    [I, "MINUS", None],
    [I, "TIMES", None],
    [I, "DIVIDE", None],
    [I, "NUMBER", None],
    [I, "LETTER", None],
    [I, "EQUALS", None],
    [I, "AND", None],
    [I, "OR", None],
    [I, "EOF", None],
    # If statement aux
    [I1, "SEMICOLON", None],
    [I1, "IF", [D, I1]],
    [I1, "LPAREN", None],
    [I1, "RPAREN", None],
    [I1, "LBRACE", None],
    [I1, "RBRACE", ["vacia"]],
    [I1, "ELSE", [D, I1]],
    [I1, "ELSE", [D, I1]],
    [I1, "INT", [D, I1]],
    [I1, "FLOAT", [D, I1]],
    [I1, "CHAR", [D, I1]],
    [I1, "VOID", [D, I1]],
    [I1, "ID", [D, I1]],
    [I1, "ASSIGN", None],
    [I1, "COMMA", None],
    [I1, "PLUS", None],
    [I1, "MINUS", None],
    [I1, "TIMES", None],
    [I1, "DIVIDE", None],
    [I1, "NUMBER", None],
    [I1, "LETTER", None],
    [I1, "EQUALS", None],
    [I1, "AND", None],
    [I1, "OR", None],
    [I1, "EOF", None],
    #  If statement aux 2
    [I2, "SEMICOLON", None],
    [I2, "IF", ["vacia"]],
    [I2, "LPAREN", None],
    [I2, "RPAREN", None],
    [I2, "LBRACE", None],
    [I2, "RBRACE", ["vacia"]],
    [I2, "ELSE", ["ELSE", "LBRACE", I1, "RBRACE"]],
    [I2, "INT", ["vacia"]],
    [I2, "FLOAT", ["vacia"]],
    [I2, "CHAR", ["vacia"]],
    [I2, "VOID", ["vacia"]],
    [I2, "ID", ["vacia"]],
    [I2, "ASSIGN", None],
    [I2, "COMMA", None],
    [I2, "PLUS", None],
    [I2, "MINUS", None],
    [I2, "TIMES", None],
    [I2, "DIVIDE", None],
    [I2, "NUMBER", None],
    [I2, "LETTER", None],
    [I2, "EQUALS", None],
    [I2, "AND", None],
    [I2, "OR", None],
    [I2, "EOF", ["vacia"]],
    # Reserved words
    [R, "SEMICOLON", None],
    [R, "IF", None],
    [R, "LPAREN", None],
    [R, "RPAREN", None],
    [R, "LBRACE", None],
    [R, "RBRACE", None],
    [R, "ELSE", None],
    [R, "INT", ["INT"]],
    [R, "FLOAT", ["FLOAT"]],
    [R, "CHAR", ["CHAR"]],
    [R, "VOID", ["VOID"]],
    [R, "ID", None],
    [R, "ASSIGN", None],
    [R, "COMMA", None],
    [R, "PLUS", None],
    [R, "MINUS", None],
    [R, "TIMES", None],
    [R, "DIVIDE", None],
    [R, "NUMBER", None],
    [R, "LETTER", None],
    [R, "EQUALS", None],
    [R, "AND", None],
    [R, "OR", None],
    [R, "EOF", None],
    # Assignment
    [A, "SEMICOLON", None],
    [A, "IF", None],
    [A, "LPAREN", None],
    [A, "RPAREN", None],
    [A, "LBRACE", None],
    [A, "RBRACE", None],
    [A, "ELSE", None],
    [A, "INT", None],
    [A, "FLOAT", None],
    [A, "CHAR", None],
    [A, "VOID", None],
    [A, "ID", ["ID", "ASSIGN", E, A1]],
    [A, "ASSIGN", None],
    [A, "COMMA", None],
    [A, "PLUS", None],
    [A, "MINUS", None],
    [A, "TIMES", None],
    [A, "DIVIDE", None],
    [A, "NUMBER", None],
    [A, "LETTER", None],
    [A, "EQUALS", None],
    [A, "AND", None],
    [A, "OR", None],
    [A, "EOF", None],
    # Assignment aux
    [A1, "SEMICOLON", ["vacia"]],
    [A1, "IF", None],
    [A1, "LPAREN", None],
    [A1, "RPAREN", None],
    [A1, "LBRACE", None],
    [A1, "RBRACE", None],
    [A1, "ELSE", None],
    [A1, "INT", None],
    [A1, "FLOAT", None],
    [A1, "CHAR", None],
    [A1, "VOID", None],
    [A1, "ID", None],
    [A1, "ASSIGN", None],
    [A1, "COMMA", ["COMMA", A]],
    [A1, "PLUS", None],
    [A1, "MINUS", None],
    [A1, "TIMES", None],
    [A1, "DIVIDE", None],
    [A1, "NUMBER", None],
    [A1, "LETTER", None],
    [A1, "EQUALS", None],
    [A1, "AND", None],
    [A1, "OR", None],
    [A1, "EOF", None],
    # Expression
    [E, "SEMICOLON", None],
    [E, "IF", None],
    [E, "LPAREN", [T, E1]],
    [E, "RPAREN", None],
    [E, "LBRACE", None],
    [E, "RBRACE", None],
    [E, "ELSE", None],
    [E, "INT", None],
    [E, "FLOAT", None],
    [E, "CHAR", None],
    [E, "VOID", None],
    [E, "ID", [T, E1]],
    [E, "ASSIGN", None],
    [E, "COMMA", None],
    [E, "PLUS", None],
    [E, "MINUS", None],
    [E, "TIMES", None],
    [E, "DIVIDE", None],
    [E, "NUMBER", [T, E1]],
    [E, "LETTER", [T, E1]],
    [E, "EQUALS", None],
    [E, "AND", None],
    [E, "OR", None],
    [E, "EOF", None],
    # Expression right to left
    [E1, "SEMICOLON", ["vacia"]],
    [E1, "IF", None],
    [E1, "LPAREN", None],
    [E1, "RPAREN", ["vacia"]],
    [E1, "LBRACE", None],
    [E1, "RBRACE", None],
    [E1, "ELSE", None],
    [E1, "INT", None],
    [E1, "FLOAT", None],
    [E1, "CHAR", None],
    [E1, "VOID", None],
    [E1, "ID", None],
    [E1, "ASSIGN", None],
    [E1, "COMMA", ["vacia"]],
    [E1, "PLUS", ["PLUS", T, E1]],
    [E1, "MINUS", ["MINUS", T, E1]],
    [E1, "TIMES", None],
    [E1, "DIVIDE", None],
    [E1, "NUMBER", None],
    [E1, "LETTER", None],
    [E1, "EQUALS", None],
    [E1, "AND", None],
    [E1, "OR", None],
    [E1, "EOF", None],
    # Expression aux
    [T, "SEMICOLON", None],
    [T, "IF", None],
    [T, "LPAREN", [F, T1]],
    [T, "RPAREN", None],
    [T, "LBRACE", None],
    [T, "RBRACE", None],
    [T, "ELSE", None],
    [T, "INT", None],
    [T, "FLOAT", None],
    [T, "CHAR", None],
    [T, "VOID", None],
    [T, "ID", [F, T1]],
    [T, "ASSIGN", None],
    [T, "COMMA", None],
    [T, "PLUS", None],
    [T, "MINUS", None],
    [T, "TIMES", None],
    [T, "DIVIDE", None],
    [T, "NUMBER", [F, T1]],
    [T, "LETTER", [F, T1]],
    [T, "EQUALS", None],
    [T, "AND", None],
    [T, "OR", None],
    [T, "EOF", None],
    # Expression left to right
    [T1, "SEMICOLON", ["vacia"]],
    [T1, "IF", None],
    [T1, "LPAREN", None],
    [T1, "RPAREN", ["vacia"]],
    [T1, "LBRACE", None],
    [T1, "RBRACE", None],
    [T1, "ELSE", None],
    [T1, "INT", None],
    [T1, "FLOAT", None],
    [T1, "CHAR", None],
    [T1, "VOID", None],
    [T1, "ID", None],
    [T1, "ASSIGN", None],
    [T1, "COMMA", ["vacia"]],
    [T1, "PLUS", ["vacia"]],
    [T1, "MINUS", ["vacia"]],
    [T1, "TIMES", ["TIMES", F, T1]],
    [T1, "DIVIDE", ["DIVIDE", F, T1]],
    [T1, "NUMBER", None],
    [T1, "LETTER", None],
    [T1, "EQUALS", [L, F, T1]],
    [T1, "AND", [L, F, T1]],
    [T1, "OR", [L, F, T1]],
    [T1, "GREATER", [L, F, T1]],
    [T1, "LESS", [L, F, T1]],
    [T1, "EOF", None],
    # Expression finish
    [F, "SEMICOLON", None],
    [F, "IF", None],
    [F, "LPAREN", ["LPAREN", E, "RPAREN"]],
    [F, "RPAREN", None],
    [F, "LBRACE", None],
    [F, "RBRACE", None],
    [F, "ELSE", None],
    [F, "INT", None],
    [F, "FLOAT", None],
    [F, "CHAR", None],
    [F, "VOID", None],
    [F, "ID", [C]],
    [F, "ASSIGN", None],
    [F, "COMMA", None],
    [F, "PLUS", None],
    [F, "MINUS", None],
    [F, "TIMES", None],
    [F, "DIVIDE", None],
    [F, "NUMBER", [C]],
    [F, "LETTER", [C]],
    [F, "EQUALS", None],
    [F, "AND", None],
    [F, "OR", None],
    [F, "EOF", None],
    # Constant
    [C, "SEMICOLON", None],
    [C, "IF", None],
    [C, "LPAREN", None],
    [C, "RPAREN", None],
    [C, "LBRACE", None],
    [C, "RBRACE", None],
    [C, "ELSE", None],
    [C, "INT", None],
    [C, "FLOAT", None],
    [C, "CHAR", None],
    [C, "VOID", None],
    [C, "ID", ["ID"]],
    [C, "ASSIGN", None],
    [C, "COMMA", None],
    [C, "PLUS", None],
    [C, "MINUS", None],
    [C, "TIMES", None],
    [C, "DIVIDE", None],
    [C, "NUMBER", ["NUMBER"]],
    [C, "LETTER", ["LETTER"]],
    [C, "EQUALS", None],
    [C, "AND", None],
    [C, "OR", None],
    [C, "EOF", None],
    # Logical operator
    [L, "SEMICOLON", None],
    [L, "IF", None],
    [L, "LPAREN", None],
    [L, "RPAREN", None],
    [L, "LBRACE", None],
    [L, "RBRACE", None],
    [L, "ELSE", None],
    [L, "INT", None],
    [L, "FLOAT", None],
    [L, "CHAR", None],
    [L, "VOID", None],
    [L, "ID", None],
    [L, "ASSIGN", None],
    [L, "COMMA", None],
    [L, "PLUS", None],
    [L, "MINUS", None],
    [L, "TIMES", None],
    [L, "DIVIDE", None],
    [L, "NUMBER", None],
    [L, "LETTER", None],
    [L, "EQUALS", ["EQUALS"]],
    [L, "AND", ["AND"]],
    [L, "OR", ["OR"]],
    [L, "GREATER", ["GREATER"]],
    [L, "LESS", ["LESS"]],
    [L, "EOF", None],
    #WHILE
    [W, "SEMICOLON", None],
    [W, "IF", None],
    [W, "LPAREN", None],
    [W, "RPAREN", None],
    [W, "LBRACE", None],
    [W, "RBRACE", None],
    [W, "ELSE", None],
    [W, "INT", None],
    [W, "FLOAT", None],
    [W, "CHAR", None],
    [W, "VOID", None],
    [W, "ID", None],
    [W, "ASSIGN", None],
    [W, "COMMA", None],
    [W, "PLUS", None],
    [W, "MINUS", None],
    [W, "TIMES", None],
    [W, "DIVIDE", None],
    [W, "NUMBER", None],
    [W, "LETTER", None],
    [W, "EQUALS", None],
    [W, "AND", None],
    [W, "OR", None],
    [W, "GREATER", None],
    [W, "LESS", None],
    [W, "EOF", None],
    [W, "WHILE", ["WHILE", "LPAREN", E, "RPAREN", "LBRACE", I1, "RBRACE"]],

]
